// class Autogenerated {
//   int? id;
//   String? title;
//   String? slug;
//   int? price;
//   String? description;
//   Category? category;
//   List<String>? images;
//   String? creationAt;
//   String? updatedAt;

//   Autogenerated({
//     this.id,
//     this.title,
//     this.slug,
//     this.price,
//     this.description,
//     this.category,
//     this.images,
//     this.creationAt,
//     this.updatedAt,
//   });

//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     title = json['title'];
//     slug = json['slug'];
//     price = json['price'];
//     description = json['description'];
//     category = json['category'] != null
//         ? new Category.fromJson(json['category'])
//         : null;
//     images = json['images'].cast<String>();
//     creationAt = json['creationAt'];
//     updatedAt = json['updatedAt'];
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['title'] = this.title;
//     data['slug'] = this.slug;
//     data['price'] = this.price;
//     data['description'] = this.description;
//     if (this.category != null) {
//       data['category'] = this.category!.toJson();
//     }
//     data['images'] = this.images;
//     data['creationAt'] = this.creationAt;
//     data['updatedAt'] = this.updatedAt;
//     return data;
//   }
// }

// class Category {
//   int? id;
//   String? name;
//   String? slug;
//   String? image;
//   String? creationAt;
//   String? updatedAt;

//   Category({
//     this.id,
//     this.name,
//     this.slug,
//     this.image,
//     this.creationAt,
//     this.updatedAt,
//   });

//   Category.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     name = json['name'];
//     slug = json['slug'];
//     image = json['image'];
//     creationAt = json['creationAt'];
//     updatedAt = json['updatedAt'];
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['name'] = this.name;
//     data['slug'] = this.slug;
//     data['image'] = this.image;
//     data['creationAt'] = this.creationAt;
//     data['updatedAt'] = this.updatedAt;
//     return data;
//   }
// }
// class Category {
//   int? id;
//   String? name;
//   String? slug;
//   String? image;
//   String? creationAt;
//   String? updatedAt;

//   bool isChecked;

//   Category({
//     this.id,
//     this.name,
//     this.slug,
//     this.image,
//     this.creationAt,
//     this.updatedAt,
//     this.isChecked = false,
//   });

//   Category.fromJson(Map<String, dynamic> json)
//       : id = json['id'],
//         name = json['name'],
//         slug = json['slug'],
//         image = json['image'],
//         creationAt = json['creationAt'],
//         updatedAt = json['updatedAt'],
//         isChecked = false;

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = <String, dynamic>{};
//     data['id'] = id;
//     data['name'] = name;
//     data['slug'] = slug;
//     data['image'] = image;
//     data['creationAt'] = creationAt;
//     data['updatedAt'] = updatedAt;

//     return data;
//   }

//   Category copyWith({
//     int? id,
//     String? name,
//     String? slug,
//     String? image,
//     String? creationAt,
//     String? updatedAt,
//     bool? isChecked,
//   }) {
//     return Category(
//       id: id ?? this.id,
//       name: name ?? this.name,
//       slug: slug ?? this.slug,
//       image: image ?? this.image,
//       creationAt: creationAt ?? this.creationAt,
//       updatedAt: updatedAt ?? this.updatedAt,
//       isChecked: isChecked ?? this.isChecked,
//     );
//   }
// }
class Category {
  int? id;
  String? name;
  String? slug;
  String? image;
  String? creationAt;
  String? updatedAt;

  bool isChecked;

  Category({
    this.id,
    this.name,
    this.slug,
    this.image,
    this.creationAt,
    this.updatedAt,
    this.isChecked = false,
  });

  Category.fromJson(Map<String, dynamic> json)
    : id = json['id'],
      name = json['name'],
      slug = json['slug'],
      image = json['image'],
      creationAt = json['creationAt'],
      updatedAt = json['updatedAt'],
      isChecked = false;

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['slug'] = slug;
    data['image'] = image;
    data['creationAt'] = creationAt;
    data['updatedAt'] = updatedAt;

    return data;
  }

  Category copyWith({
    int? id,
    String? name,
    String? slug,
    String? image,
    String? creationAt,
    String? updatedAt,
    bool? isChecked,
  }) {
    return Category(
      id: id ?? this.id,
      name: name ?? this.name,
      slug: slug ?? this.slug,
      image: image ?? this.image,
      creationAt: creationAt ?? this.creationAt,
      updatedAt: updatedAt ?? this.updatedAt,
      isChecked: isChecked ?? this.isChecked,
    );
  }
}
